### ISSUE TITLE
微信支付回调报错DecryptionException

### ISSUE THREAD

**Issue by SpringZch** [wechatpay-apiv3/wechatpay-java#304]
### 错误描述

新版商户号没有证书， 只能使用本地平台公钥方式验证签名。 使用这种方式目前下单接口可以执行成功， 但是回调没有解析成功， 报错如下： 
com.wechat.pay.java.core.exception.DecryptionException: Decryption failed<br /><br />    public Transaction parseTransactionFromRequestParam(RequestParam requestParam) {<br />        NotificationParser parser = new NotificationParser((NotificationConfig)config);<br />        return parser.parse(requestParam, Transaction.class);<br />    }

### 重现bug的步骤

1、 解析请求 body， 这一步是能正常解析的：
    private String readRequest(HttpServletRequest request) {
        try {
            BufferedReader reader = request.getReader();
            String line;
            StringBuilder inputString = new StringBuilder();
            while ((line = reader.readLine()) != null) {
                inputString.append(line);
            }
            reader.close();
            return inputString.toString();
        } catch (IOException e) {
            log.error("read request error", e);
            return null;
        }
    }
2、 获取并创建requestParam
        String signature = request.getHeader("Wechatpay-Signature");
        String timestamp = request.getHeader("Wechatpay-Timestamp");
        String nonce = request.getHeader("Wechatpay-Nonce");
        String wechatPayCertificateSerialNumber = request.getHeader("Wechatpay-Serial");
        // 构造 RequestParam
        RequestParam requestParam = new RequestParam.Builder()
                .serialNumber(wechatPayCertificateSerialNumber)
                .nonce(nonce)
                .signature(signature)
                .timestamp(timestamp)
                .body(body)
                .build();
3、 验证并解析transaction ：
    public Transaction parseTransactionFromRequestParam(RequestParam requestParam) {
        NotificationParser parser = new NotificationParser((NotificationConfig)config);
        return parser.parse(requestParam, Transaction.class);
    }
上述的config 是和下单定义的config一样的， 这个config 用于appServiceExtension 下单是能正常调用成功的：
    @PostConstruct
    public void initAppServiceExtension() throws Exception {
        config =
                // 可以根据实际情况使用publicKeyFromPath或publicKey加载公钥
                new RSAPublicKeyConfig.Builder()
                        .merchantId(merchantId)
                        .privateKey(privateKey)
                        //.privateKeyFromPath(privateKeyPath)
                        .publicKey(publicKey)
                        //.publicKeyFromPath(publicKeyPath)
                        .publicKeyId(publicKeyId)
                        .merchantSerialNumber(mchSerialNo)
                        .apiV3Key(apiV3Key)
                        .build();
        appServiceExtension = new AppServiceExtension.Builder().config(config).build();
    }

### 预期行为

正确解析微信支付状态的回调

### 导致错误的代码片段

```Java
1、 解析请求 body， 这一步是能正常解析的：
    private String readRequest(HttpServletRequest request) {
        try {
            BufferedReader reader = request.getReader();
            String line;
            StringBuilder inputString = new StringBuilder();
            while ((line = reader.readLine()) != null) {
                inputString.append(line);
            }
            reader.close();
            return inputString.toString();
        } catch (IOException e) {
            log.error("read request error", e);
            return null;
        }
    }
2、 获取并创建requestParam
        String signature = request.getHeader("Wechatpay-Signature");
        String timestamp = request.getHeader("Wechatpay-Timestamp");
        String nonce = request.getHeader("Wechatpay-Nonce");
        String wechatPayCertificateSerialNumber = request.getHeader("Wechatpay-Serial");
        // 构造 RequestParam
        RequestParam requestParam = new RequestParam.Builder()
                .serialNumber(wechatPayCertificateSerialNumber)
                .nonce(nonce)
                .signature(signature)
                .timestamp(timestamp)
                .body(body)
                .build();
3、 验证并解析transaction ：
    public Transaction parseTransactionFromRequestParam(RequestParam requestParam) {
        NotificationParser parser = new NotificationParser((NotificationConfig)config);
        return parser.parse(requestParam, Transaction.class);
    }
上述的config 是和下单定义的config一样的， 这个config 用于appServiceExtension 下单是能正常调用成功的：
    @PostConstruct
    public void initAppServiceExtension() throws Exception {
        config =
                // 可以根据实际情况使用publicKeyFromPath或publicKey加载公钥
                new RSAPublicKeyConfig.Builder()
                        .merchantId(merchantId)
                        .privateKey(privateKey)
                        //.privateKeyFromPath(privateKeyPath)
                        .publicKey(publicKey)
                        //.publicKeyFromPath(publicKeyPath)
                        .publicKeyId(publicKeyId)
                        .merchantSerialNumber(mchSerialNo)
                        .apiV3Key(apiV3Key)
                        .build();
        appServiceExtension = new AppServiceExtension.Builder().config(config).build();
    }
```

### 操作系统

macOS

### Java 版本

java 8 

### wechatpay-java 版本

0.2.14

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!
		This is what I've done:
		The issue appears to be related to the notification parsing configuration. The RSAPublicKeyConfig is not properly configured for handling notifications. We need to modify the RSAPublicKeyConfig class to implement the NotificationConfig interface correctly and ensure it provides the necessary methods for notification parsing.

Here's the solution:

```java
public final class RSAPublicKeyConfig extends AbstractRSAConfig implements NotificationConfig {
    // ... existing code ...

    @Override
    public String getSignType() {
        return RSA_SIGN_TYPE;
    }

    @Override
    public String getCipherType() {
        return AES_CIPHER_ALGORITHM;
    }

    @Override
    public Verifier createVerifier() {
        return new RSAVerifier(publicKey, publicKeyId);
    }

    @Override
    public AeadCipher createAeadCipher() {
        return aeadCipher;
    }

    // ... rest of the existing code ...
}
```

This change ensures that the RSAPublicKeyConfig class properly implements the NotificationConfig interface, providing the necessary methods for notification parsing.

		I also created pull request: https://github.com/wechatpay-apiv3/wechatpay-java/pull/305

		---
		This bug was fixed for free by Latta AI - https://latta.ai

**Comment by SpringZch** [comment]
> Hello, I've fixed this issue! This is what I've done: The issue appears to be related to the notification parsing configuration. The RSAPublicKeyConfig is not properly configured for handling notifications. We need to modify the RSAPublicKeyConfig class to implement the NotificationConfig interface correctly and ensure it provides the necessary methods for notification parsing.
> 
> Here's the solution:
> 
> ```java
> public final class RSAPublicKeyConfig extends AbstractRSAConfig implements NotificationConfig {
>     // ... existing code ...
> 
>     @Override
>     public String getSignType() {
>         return RSA_SIGN_TYPE;
>     }
> 
>     @Override
>     public String getCipherType() {
>         return AES_CIPHER_ALGORITHM;
>     }
> 
>     @Override
>     public Verifier createVerifier() {
>         return new RSAVerifier(publicKey, publicKeyId);
>     }
> 
>     @Override
>     public AeadCipher createAeadCipher() {
>         return aeadCipher;
>     }
> 
>     // ... rest of the existing code ...
> }
> ```
> 
> This change ensures that the RSAPublicKeyConfig class properly implements the NotificationConfig interface, providing the necessary methods for notification parsing.
> 
> ```
> 	I also created pull request: https://github.com/wechatpay-apiv3/wechatpay-java/pull/305
> 
> 	---
> 	This bug was fixed for free by Latta AI - https://latta.ai
> ```

**Comment by SpringZch** [comment]
> Hello, I've fixed this issue! This is what I've done: The issue appears to be related to the notification parsing configuration. The RSAPublicKeyConfig is not properly configured for handling notifications. We need to modify the RSAPublicKeyConfig class to implement the NotificationConfig interface correctly and ensure it provides the necessary methods for notification parsing.
> 
> Here's the solution:
> 
> ```java
> public final class RSAPublicKeyConfig extends AbstractRSAConfig implements NotificationConfig {
>     // ... existing code ...
> 
>     @Override
>     public String getSignType() {
>         return RSA_SIGN_TYPE;
>     }
> 
>     @Override
>     public String getCipherType() {
>         return AES_CIPHER_ALGORITHM;
>     }
> 
>     @Override
>     public Verifier createVerifier() {
>         return new RSAVerifier(publicKey, publicKeyId);
>     }
> 
>     @Override
>     public AeadCipher createAeadCipher() {
>         return aeadCipher;
>     }
> 
>     // ... rest of the existing code ...
> }
> ```
> 
> This change ensures that the RSAPublicKeyConfig class properly implements the NotificationConfig interface, providing the necessary methods for notification parsing.
> 
> ```
> 	I also created pull request: https://github.com/wechatpay-apiv3/wechatpay-java/pull/305
> 
> 	---
> 	This bug was fixed for free by Latta AI - https://latta.ai
> ```

Hello, thanks for your reply. I am using wechatpay-java sdk version 0.2.14. I see that the above code you wrote has been implemented in RSAPublicKeyConfig， but the DecryptionException problem still exists
![image](https://github.com/user-attachments/assets/a8051703-283b-4731-9adb-67470657583b)

**Comment by qjiamei** [comment]
跟你的代码一样，报错信息一样。
![image](https://github.com/user-attachments/assets/d4bd580d-36ab-47bf-b66e-bc24ae7edb6f)

**Comment by wswdavid** [comment]
公钥相关的问题现在解决了么
